// PLAYWRIGHT_MODULE points to an already installed Playwright package (no installation).
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const out = '/tmp/ramia22-games-design-evidence';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 960 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:4318/') ? route.continue() : route.abort());
  await page.goto('http://127.0.0.1:4318/gipf/');
  await page.screenshot({ path: `${out}/desktop.png`, fullPage: true });
  const links = page.getByRole('navigation').getByRole('link');
  assert.equal(await links.count(), 6);
  assert.deepEqual(await links.evaluateAll(nodes => nodes.map(n => n.getAttribute('href'))), ['/gipf/yinsh','/gipf/zertz','/gipf/chess','/gipf/catan','/gipf/splendor','/gipf/diplomacy']);
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => document.activeElement.getAttribute('href')), '/gipf/yinsh');
  assert.equal(await page.evaluate(() => getComputedStyle(document.activeElement).outlineWidth), '3px');
  await page.screenshot({ path: `${out}/keyboard-focus.png`, fullPage: true });
  await page.keyboard.press('Enter');
  await page.getByRole('heading', { name: 'Guest game destination' }).waitFor();
  assert.equal(new URL(page.url()).pathname, '/gipf/yinsh');
  console.log('PASS six registry/base-path links and keyboard guest launch (destination stub)');
  await page.goto('http://127.0.0.1:4318/gipf/');
  for (const width of [480, 320]) {
    await page.setViewportSize({ width, height: 900 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: `${out}/mobile-${width}.png`, fullPage: true });
  }
  await page.getByRole('button', { name: 'Sign in / Create account' }).click();
  await page.getByLabel('Username', { exact: true }).fill('Synthetic player');
  await page.getByLabel('Password', { exact: true }).fill('synthetic-password');
  assert.equal(await page.getByRole('checkbox').isChecked(), false);
  await page.getByRole('button', { name: 'Show password' }).click();
  assert.equal(await page.getByLabel('Password', { exact: true }).getAttribute('type'), 'text');
  await page.getByRole('button', { name: 'Hide password' }).click();
  await page.evaluate(() => sessionStorage.setItem('fixture-error', 'true'));
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').textContent(), /Wrong username/);
  await page.screenshot({ path: `${out}/mobile-error.png`, fullPage: true });
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByLabel('Confirm password', { exact: true }).fill('mismatch');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  assert.match(await page.getByRole('alert').textContent(), /don't match/);
  await page.getByLabel('Confirm password', { exact: true }).fill('synthetic-password');
  assert(await page.getByText(/There is no password reset/).isVisible());
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: `${out}/mobile-create.png`, fullPage: true });
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByText('Signed in as Synthetic player').waitFor();
  assert.equal(await page.evaluate(() => sessionStorage.getItem('fixture-import')), 'true');
  console.log('PASS 480/320 overflow, labels, visibility toggle, errors, confirmation, recovery warning and explicit guest import');
  await page.getByRole('button', { name: 'Sign out', exact: true }).focus();
  await page.keyboard.press('Enter');
  assert(await page.getByText(/Unsynced progress stays encrypted/).isVisible());
  await page.screenshot({ path: `${out}/mobile-signout.png`, fullPage: true });
  await page.getByRole('button', { name: 'Cancel', exact: true }).focus();
  await page.keyboard.press('Enter');
  assert(await page.getByText('Signed in as Synthetic player').isVisible());
  await page.getByRole('button', { name: 'Sign out', exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Sign out', exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.getByRole('button', { name: 'Sign in / Create account' }).waitFor();
  await page.evaluate(() => sessionStorage.removeItem('fixture-error'));
  await page.getByRole('button', { name: 'Sign in / Create account' }).click();
  await page.getByLabel('Username', { exact: true }).fill('Synthetic player');
  await page.getByLabel('Password', { exact: true }).fill('synthetic-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).focus();
  await page.keyboard.press('Enter');
  await page.getByText('Signed in as Synthetic player').waitFor();
  assert.equal(await page.evaluate(() => sessionStorage.getItem('fixture-import')), 'false');
  assert(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches));
  assert(await page.locator('.landing-page *').evaluateAll(nodes => nodes.every(n => getComputedStyle(n).animationName === 'none' && getComputedStyle(n).transitionDuration === '0s')));
  assert.deepEqual(errors, []);
  console.log('PASS keyboard signout cancel/confirm and sign-in, default import off, reduced motion and no browser errors');
  const luminance = hex => {
    const channels = hex.match(/\w\w/g).map(c => parseInt(c, 16) / 255).map(c => c <= .04045 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4);
    return channels[0] * .2126 + channels[1] * .7152 + channels[2] * .0722;
  };
  for (const [fg, bg] of [['17253d','fafcff'],['526279','fafcff'],['3156ba','fafcff'],['526279','e8effa'],['17253d','e8effa'],['9c2525','e8effa'],['644212','fff3d6'],['ffffff','3156ba']]) {
    const values = [luminance(fg), luminance(bg)].sort((a,b) => b-a);
    const ratio = (values[0]+.05)/(values[1]+.05);
    assert(ratio >= 4.5);
    console.log(`PASS text contrast #${fg}/#${bg}: ${ratio.toFixed(2)}:1`);
  }
  console.log(`Screenshots: ${out}`);
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
